import { TarotCard } from '../entities/tarot-card.entity';

/**
 * 塔罗牌基础数据
 */
export const tarotCardsData: Partial<TarotCard>[] = [
  // 大阿卡纳牌 (Major Arcana)
  {
    nameCn: '愚者',
    name: 'The Fool',
    type: 'major',
    number: 0,
    uprightKeywords: '新开始,冒险,纯真,自由',
    reversedKeywords: '鲁莽,愚蠢,风险,缺乏方向',
    uprightMeaning: '愚者代表新的开始和无限的可能性。这是一张充满希望和冒险精神的牌，暗示着你即将踏上一段新的人生旅程。',
    reversedMeaning: '逆位的愚者可能表示鲁莽行事或缺乏深思熟虑。需要更加谨慎地考虑你的选择和行动。',
    description: '愚者站在悬崖边，手持白玫瑰，象征纯洁和新的开始。他的脚步轻盈，准备踏上未知的旅程。',
    imageUrl: '/images/tarot/major/00-fool.jpg',
    element: 'air',
    astrology: 'Uranus',
    numerologyMeaning: '新开始的数字0代表无限可能',
  },
  {
    nameCn: '魔术师',
    name: 'The Magician',
    type: 'major',
    number: 1,
    uprightKeywords: '意志力,创造力,技能,专注',
    reversedKeywords: '操控,欺骗,缺乏技能,分散注意力',
    uprightMeaning: '魔术师代表意志力和创造力的完美结合。你拥有实现目标所需的所有工具和技能。',
    reversedMeaning: '逆位的魔术师可能暗示滥用权力或缺乏专注。需要重新审视你的动机和方法。',
    description: '魔术师举起魔杖，桌上摆放着四大元素的象征物，代表他掌握了所有必要的工具。',
    imageUrl: '/images/tarot/major/01-magician.jpg',
    element: 'air',
    astrology: 'Mercury',
    numerologyMeaning: '数字1代表开始和领导力',
  },
  {
    nameCn: '女祭司',
    name: 'The High Priestess',
    type: 'major',
    number: 2,
    uprightKeywords: '直觉,神秘,潜意识,智慧',
    reversedKeywords: '缺乏直觉,秘密,表面知识',
    uprightMeaning: '女祭司代表内在智慧和直觉力量。她提醒你倾听内心的声音，相信你的直觉。',
    reversedMeaning: '逆位的女祭司可能表示与直觉失去联系，或者过度依赖理性思维。',
    description: '女祭司坐在神殿中，身后是象征知识的柱子，她掌握着神秘的智慧。',
    imageUrl: '/images/tarot/major/02-high-priestess.jpg',
    element: 'water',
    astrology: 'Moon',
    numerologyMeaning: '数字2代表平衡和合作',
  },
  {
    nameCn: '皇后',
    name: 'The Empress',
    type: 'major',
    number: 3,
    uprightKeywords: '丰饶,母性,创造,自然',
    reversedKeywords: '依赖,空虚,缺乏成长',
    uprightMeaning: '皇后代表丰饶和创造力。她象征着母性的力量和自然的恩赐。',
    reversedMeaning: '逆位的皇后可能暗示创造力受阻或过度依赖他人。',
    description: '皇后坐在自然环境中，周围充满了生机勃勃的植物，象征着生命力和创造力。',
    imageUrl: '/images/tarot/major/03-empress.jpg',
    element: 'earth',
    astrology: 'Venus',
    numerologyMeaning: '数字3代表创造和表达',
  },
  {
    nameCn: '皇帝',
    name: 'The Emperor',
    type: 'major',
    number: 4,
    uprightKeywords: '权威,结构,控制,稳定',
    reversedKeywords: '专制,缺乏纪律,不稳定',
    uprightMeaning: '皇帝代表权威和稳定的结构。他象征着领导力和建立秩序的能力。',
    reversedMeaning: '逆位的皇帝可能表示滥用权力或缺乏自律。',
    description: '皇帝坐在王座上，手持权杖，象征着世俗的权力和控制力。',
    imageUrl: '/images/tarot/major/04-emperor.jpg',
    element: 'fire',
    astrology: 'Aries',
    numerologyMeaning: '数字4代表稳定和基础',
  },
  
  // 小阿卡纳牌 - 权杖牌组 (Wands)
  {
    nameCn: '权杖王牌',
    name: 'Ace of Wands',
    type: 'minor',
    suit: 'wands',
    number: 1,
    uprightKeywords: '新项目,创造力,灵感,潜力',
    reversedKeywords: '缺乏方向,创造力受阻,延迟',
    uprightMeaning: '权杖王牌代表新的创意项目和无限的潜力。这是开始新事业或追求激情的绝佳时机。',
    reversedMeaning: '逆位可能表示创意受阻或缺乏明确的方向。需要重新点燃你的热情。',
    description: '一只手从云中伸出，握着一根绿叶茂盛的权杖，象征着新的开始和生命力。',
    imageUrl: '/images/tarot/wands/ace-wands.jpg',
    element: 'fire',
    astrology: 'Fire signs',
    numerologyMeaning: '王牌代表新的开始和纯粹的能量',
  },
  {
    nameCn: '权杖二',
    name: 'Two of Wands',
    type: 'minor',
    suit: 'wands',
    number: 2,
    uprightKeywords: '规划,进展,决策,个人力量',
    reversedKeywords: '缺乏规划,恐惧,缺乏控制',
    uprightMeaning: '权杖二代表制定长远计划和掌控自己的命运。你正在为未来做出重要决策。',
    reversedMeaning: '逆位可能表示缺乏明确的计划或对未来感到不确定。',
    description: '一个人站在城堡上，手持地球仪，眺望远方，象征着规划和远见。',
    imageUrl: '/images/tarot/wands/two-wands.jpg',
    element: 'fire',
    astrology: 'Mars in Aries',
    numerologyMeaning: '数字2代表选择和平衡',
  },
  
  // 小阿卡纳牌 - 圣杯牌组 (Cups)
  {
    nameCn: '圣杯王牌',
    name: 'Ace of Cups',
    type: 'minor',
    suit: 'cups',
    number: 1,
    uprightKeywords: '新的爱情,情感觉醒,直觉,精神成长',
    reversedKeywords: '情感封闭,失望,缺乏爱',
    uprightMeaning: '圣杯王牌代表情感的新开始和精神的觉醒。爱情和直觉将指引你的道路。',
    reversedMeaning: '逆位可能表示情感上的困难或与内心感受失去联系。',
    description: '一只手从云中伸出，握着溢出水流的圣杯，象征着情感的丰盛和精神的恩赐。',
    imageUrl: '/images/tarot/cups/ace-cups.jpg',
    element: 'water',
    astrology: 'Water signs',
    numerologyMeaning: '王牌代表情感的纯粹形式',
  },
  
  // 小阿卡纳牌 - 宝剑牌组 (Swords)
  {
    nameCn: '宝剑王牌',
    name: 'Ace of Swords',
    type: 'minor',
    suit: 'swords',
    number: 1,
    uprightKeywords: '新想法,心智清晰,突破,真理',
    reversedKeywords: '混乱,缺乏清晰,误解',
    uprightMeaning: '宝剑王牌代表心智的突破和新的洞察力。真理将被揭示，思路变得清晰。',
    reversedMeaning: '逆位可能表示思维混乱或缺乏明确的方向。',
    description: '一只手从云中伸出，握着一把双刃剑，剑尖戴着桂冠，象征着胜利和真理。',
    imageUrl: '/images/tarot/swords/ace-swords.jpg',
    element: 'air',
    astrology: 'Air signs',
    numerologyMeaning: '王牌代表思想的纯粹力量',
  },
  
  // 小阿卡纳牌 - 星币牌组 (Pentacles)
  {
    nameCn: '星币王牌',
    name: 'Ace of Pentacles',
    type: 'minor',
    suit: 'pentacles',
    number: 1,
    uprightKeywords: '新机会,物质成功,繁荣,安全',
    reversedKeywords: '错失机会,缺乏规划,物质损失',
    uprightMeaning: '星币王牌代表物质世界的新机会和繁荣的开始。财务状况将得到改善。',
    reversedMeaning: '逆位可能表示错失机会或财务规划不当。',
    description: '一只手从云中伸出，握着一枚金色的星币，下方是美丽的花园，象征着物质的丰盛。',
    imageUrl: '/images/tarot/pentacles/ace-pentacles.jpg',
    element: 'earth',
    astrology: 'Earth signs',
    numerologyMeaning: '王牌代表物质世界的新开始',
  },
];